#!/bin/bash
#
source "$(dirname "$0")/get-script-header.sh"
if [ -e drat-trim ]; then
  echo 'error: file or directory "drat-trim" exists; please move it out of the way.' >&2
  exit 1
fi

git clone https://github.com/alex-ozdemir/drat-trim.git

cd drat-trim

make install

echo
echo ===================== Now configure CVC4 with =====================
echo ./configure.sh --drat-trim
