id     = "FF"
name   = "Finite Field Theory"

[[option]]
  name       = "ffMeasureConflictQuality"
  category   = "expert"
  long       = "ff-measure-conflict-quality"
  type       = "bool"
  default    = "false"
  help       = "brute-force the smallest conflict"

[[option]]
  name       = "ffUseToyGb"
  category   = "expert"
  long       = "ff-use-toy-gb"
  type       = "bool"
  default    = "false"
  help       = "use the toy groebner basis engine"

[[option]]
  name       = "ffTraceToyGb"
  category   = "expert"
  long       = "ff-trace-toy-gb"
  type       = "bool"
  default    = "false"
  help       = "use the traced toy groebner basis engine"

[[option]]
  name       = "ffCheckTraceToyGb"
  category   = "expert"
  long       = "ff-check-trace-toy-gb"
  type       = "bool"
  default    = "false"
  help       = "check the traced toy groebner basis engine against the untraced variant"
