id     = "FF"
name   = "Finite Field Theory"

[[option]]
  name       = "ffTraceGb"
  category   = "expert"
  long       = "ff-trace-gb"
  type       = "bool"
  default    = "true"
  help       = "use a traced groebner basis engine"

[[option]]
  name       = "ffFieldPolys"
  category   = "expert"
  long       = "ff-field-polys"
  type       = "bool"
  default    = "false"
  help       = "include field polynomials in Groebner basis computation; don't do this"

[[option]]
  name       = "ffDisjunctiveBit"
  category   = "expert"
  long       = "ff-disjunctive-bit"
  type       = "bool"
  default    = "true"
  help       = "leave disjunctive bit constraints (or (= x 1) (= x 0)) alone; otherwise, preprocess to (= (* x x) x)"

[[option]]
  name       = "ffBitsum"
  category   = "expert"
  long       = "ff-bitsum"
  type       = "bool"
  default    = "false"
  help       = "parse bitsums"


[[option]]
  name       = "ffSolver"
  category   = "expert"
  long       = "ff-solver=MODE"
  type       = "FfSolver"
  default    = "GB"
  help       = "which field solver (default: 'gb'; see --ff-solver=help)"
  help_mode  = "Which field solver"
[[option.mode.GB]]
  name = "gb"
  help = "use a groebner basis for the whole system"
[[option.mode.SPLIT_GB]]
  name = "split"
  help = "use multiple groebner bases for partitions of the system"

[[option]]
  name       = "ffSplitDriverBasis"
  long       = "ff-split-driver-basis=I"
  category   = "expert"
  type       = "uint64_t"
  minimum    = "0"
  maximum    = "1"
  default    = "0"
  help       = "In Split solver: which basis drives model construction"
[[option]]
  name       = "ffSplitFullIntProp"
  long       = "ff-split-full-int-prop"
  category   = "expert"
  type       = "bool"
  default    = "false"
  help       = "In Split solver: complete inter-basis propagation"
[[option]]
  name       = "ffSplitNoExtProp"
  long       = "ff-split-no-ext-prop"
  category   = "expert"
  type       = "bool"
  default    = "false"
  help       = "In Split solver: no extra propagation"
[[option]]
  name       = "ffSplitNoIntProp"
  long       = "ff-split-no-int-prop"
  category   = "expert"
  type       = "bool"
  default    = "false"
  help       = "In Split solver: no inter-basis propagation"
[[option]]
  name       = "ffSplitDenserProp"
  long       = "ff-split-denser-prop"
  category   = "expert"
  type       = "bool"
  default    = "false"
  help       = "In Split solver: sparse basis accepts all p with deg(p) <= 1 and vars(p) <= 16"
[[option]]
  name       = "ffSplitQuadProp"
  long       = "ff-split-quad-prop"
  category   = "expert"
  type       = "bool"
  default    = "false"
  help       = "In Split solver: 'linear' basis accepts all p with deg(p) <= 2"
