id     = "FF"
name   = "Finite Field Theory"

[[option]]
  name       = "ffTraceGb"
  category   = "expert"
  long       = "ff-trace-gb"
  type       = "bool"
  default    = "true"
  help       = "use a traced groebner basis engine"

[[option]]
  name       = "ffFieldPolys"
  category   = "expert"
  long       = "ff-field-polys"
  type       = "bool"
  default    = "false"
  help       = "include field polynomials in Groebner basis computation; don't do this"

[[option]]
  name       = "ffRangeSolver"
  category   = "expert"
  long       = "ff-range-solver"
  type       = "bool"
  default    = "false"
  help       = "use the range solver"

[[option]]
  name       = "ffQuotientRanges"
  category   = "expert"
  long       = "ff-quotient-ranges"
  type       = "bool"
  default    = "true"
  help       = "bound quotient ranges in the range solver"
